image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install -g now
    - now secrets add spotify-client-id ${SPOTIFY_CLIENT_ID}
    - now secrets add spotify-client-secret ${SPOTIFY_CLIENT_SECRET}
    - now secrets add spotify-access-token ${SPOTIFY_ACCESS_TOKEN}
    - now secrets add spotify-refresh-token ${SPOTIFY_REFRESH_TOKEN}
    - now --token ${NOW_TOKEN} --prod


